services:
  application:
    build: .
    container_name: "application"
    ports:
      - "5070:5050"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env

  postgres:
    image: postgres:16-bookworm
    container_name: "postgres"
    env_file:
      - .env
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
      image: migrate/migrate
      volumes:
        - ./migrations:/migrations
      command: ["-path", "/migrations", "-database", "${CONN_STRING}", "up"]
      depends_on:
        postgres:
          condition: service_healthy
      env_file:
        - .env